server:
  port: 8762
spring:  application:    name: Order-Service
  datasource:    url: jdbc:mysql://localhost:3306/kali
    username: root
    password: root
  jpa:
    show-sql: true    hibernate:      ddl-auto: create
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost